deodex: Add deodexing boot jars support
PS: Loops can be simplified but I'm lazy... This works :p

diff --git a/bin/deodex b/bin/deodex
--- a/bin/deodex
+++ b/bin/deodex
@@ -1,18 +1,7 @@
 #!/usr/bin/env bash
 
-# REQUIREMENT: cd into $ROM_DUMP/system & then proceed
-
-# COLORS
-lightgray='\e[0;37m'
-darkgray='\e[1;30m'
-lightblue='\e[1;34m'
-lightgreen='\e[1;32m'
-lightcyan='\e[1;36m'
-lightred='\e[1;31m'
-lightpurple='\e[1;35m'
-yellow='\e[1;33m'
-white='\e[1;37m'
-nc='\e[0m'
+# source functions
+source ~/.dotfiles/functions
 
 # Make temp work dir
 TMPDIR=$(mktemp -d)
@@ -21,6 +10,12 @@ HOST="$(uname)"
 
 if [ "$#" -lt 1 ]; then
     echo "You have to specify at least one app to deodex"
+    exit 1
+fi
+
+# REQUIREMENT: cd into $ROM_DUMP/system
+if [[ ! -d framework ]]; then
+    echo -e "${lightred}Please make sure to cd into \$ROM_DUMP/system first.${nc}"
     exit 1
 fi
 
@@ -41,6 +36,7 @@ if [[ -z $BAKSMALIJAR || -z $SMALIJAR ]]; then
         export SMALIJAR=$C_LINEAGEDIR/vendor/lineage/build/tools/smali/smali.jar
     else
         echo -e "${lightred}baksmali.jar &/ smali.jar not found!${nc}"
+        echo -e "${lightred}Export \$BAKSMALIJAR & \$SMALIJAR paths for baksmali.jar & smali.jar to continue...${nc}"
         exit 1
     fi
 fi
@@ -53,6 +49,7 @@ if [ -z "$VDEXEXTRACTOR" ]; then
         export VDEXEXTRACTOR="$C_LINEAGEDIR"/vendor/lineage/build/tools/"$HOST"/vdexExtractor
     else
         echo -e "${lightred}vdexExtractor not found!${nc}"
+        echo -e "${lightred}Export \$VDEXEXTRACTOR path for vdexExtractor bin to continue...${nc}"
         exit 1
     fi
 fi
@@ -61,6 +58,7 @@ if [[ -z "$CDEXCONVERTER" ]]; then
         export CDEXCONVERTER=$(find "$C_ANDROIDTOOLSDIR"/vdexExtractor -name compact_dex_converter)
     else
         echo -e "${lightred}compact_dex_converter not found!${nc}"
+        echo -e "${lightred}Export \$CDEXCONVERTER path for compact_dex_converter bin to continue...${nc}"
         exit 1
     fi
 fi
@@ -78,10 +76,22 @@ for module in $@; do
             APPDIR=$(find * -type d -name "$FNAME")
             OAT=$(readlink -f $APPDIR/oat/$device_arch)
         elif [[ $module = *.jar ]]; then
-            OAT=$(readlink -f framework/oat/$device_arch)
+            if [[ ! -z $(ls framework/oat/$device_arch | grep $FNAME) ]]; then
+                OAT=$(readlink -f framework/oat/$device_arch)
+            elif [[ ! -z $(ls framework | grep boot-$FNAME) ]]; then
+                echo -e "${darkgray}Boot jar detected...${nc}"
+                BOOTJAR=true
+            else
+                echo -e "${lightred}Couldn't find .odex or .vdex for following jar: $FILE"
+                exit 1
+            fi
         fi
         DEX=$(readlink -f $OAT/$FNAME.odex)
         VDEX=$(readlink -f $OAT/$FNAME.vdex)
+        if [[ $BOOTJAR ]]; then
+            VDEX=$(readlink -f framework/boot-$FNAME.vdex)
+            FNAME="boot-${FNAME}"
+        fi
 
         # Make backup
         cp $FPATH ${FPATH}.oldbak
